[[CUDA_Compiler]]
arch = "x86_64"
cuda = "11"
git-tree-sha1 = "aa53d87db1ebd36aaf53bebd4d06d025517292e2"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "d59a49b8746655dad4ac2d5f27372eb213d20da1f26a5c25727f1d0ac272587a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.x86_64-linux-gnu-cuda+11.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "11"
cuda_platform = "jetson"
git-tree-sha1 = "e5813ac58b243fe277e4d8005e0e533596323151"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "d1ab514a468342c864e81dc3cf4def4c1a22046b3ba7c5061fe3aa4f1f4765cc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.aarch64-linux-gnu-cuda_platform+jetson-cuda+11.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "11"
cuda_platform = "sbsa"
git-tree-sha1 = "b867f0614c8572b8c9100d0a82eaa7b7e0f62733"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "eedcd58cec8b20f8faadaaebf391b532e1379f65e5520b8918ecc7e7f60d5c41"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "11"
git-tree-sha1 = "bb072af73164da4c04847cd8d4dfe98c11afc618"
lazy = true
os = "windows"

    [[CUDA_Compiler.download]]
    sha256 = "bcf46729ca3f592b49338c422e3dfda24a6037d937e021cbb110096488fdb571"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.x86_64-w64-mingw32-cuda+11.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "12"
git-tree-sha1 = "486b1a24f652206e8b1369615e163ab59ef0152c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "c268e4a7c0ff5a884c54fb0130f445d1a3f2612c569bd82e0f3dce580f4dab42"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.x86_64-linux-gnu-cuda+12.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "12"
cuda_platform = "jetson"
git-tree-sha1 = "974384b73e97bba37a413a5785b9a94a5712c625"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "0684fea3b64ed51179236a18091626568938fe483f10c61ff92314ab0b5a4038"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "12"
cuda_platform = "sbsa"
git-tree-sha1 = "bfcb6e5ba036628bdde45c9a9a54341b4c81e3bb"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "6ad74a801e53f1a6897357b4bcb83148596692f1e6c96ba0317171e17d77960f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "12"
git-tree-sha1 = "813495e9c171f5894132fcae7d2f26d24d52a4db"
lazy = true
os = "windows"

    [[CUDA_Compiler.download]]
    sha256 = "f980151a37f47b3f527c62a68a4642c3b490916b2123c2e798690946bdddd59a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.x86_64-w64-mingw32-cuda+12.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "13"
git-tree-sha1 = "55bc4406b8637bbcdf7c2de8055de5635698d43d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "258a24f5a8ac2e817acd1fbdd2244f87721365715ade2e7249c703ee3f3f925b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.x86_64-linux-gnu-cuda+13.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "13"
git-tree-sha1 = "69bdf76bbdb308cd1ff59e6b8ba6ed4d6799ff09"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "36b1771045ca039f972ef23e6315823ff5900efe9fcbd887c98008812ad0d8d4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.aarch64-linux-gnu-cuda+13.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "13"
git-tree-sha1 = "f72aee0e5c6c22fbd40686c71d038741dfadab21"
lazy = true
os = "windows"

    [[CUDA_Compiler.download]]
    sha256 = "15f324bc12ab00b6bd8338c98bd51b4b1b442a47e7298f3b153b2f34c8e30ad5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.4.1+1/CUDA_Compiler.v0.4.1.x86_64-w64-mingw32-cuda+13.tar.gz"
