[[CUDA_Compiler]]
arch = "x86_64"
cuda = "11"
git-tree-sha1 = "93ee1eba7bb5f16a487d3ae19005b8d6c003843b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "0d656f3107ca484ba06a515f711e1ef39d3fd0a47f9a083cd6ad9eb4f9b3156c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.x86_64-linux-gnu-cuda+11.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "11"
cuda_platform = "jetson"
git-tree-sha1 = "a18c9dc92ef8326fd370781a09df44a920601aed"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "a5b302141daf065ff408203d4c4080d921eaed49eab28c110bec6042caa58fca"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.aarch64-linux-gnu-cuda_platform+jetson-cuda+11.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "11"
cuda_platform = "sbsa"
git-tree-sha1 = "286d18be6b2567c35ccad53eee85828b97d14e82"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "dad6576022dfaf70ce515fda5787a03c1ef0e4d0b287eab3173711f223a2c922"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "11"
git-tree-sha1 = "9a3edbc27d254645065e0eb0d3eadf223ba09d5c"
lazy = true
os = "windows"

    [[CUDA_Compiler.download]]
    sha256 = "377c5582a3aa77320fefbf2f021855b619caba71b65355b5efb75552f21bbb35"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.x86_64-w64-mingw32-cuda+11.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "12"
git-tree-sha1 = "5de99ad895d4656bf23b60faaec6ddd55a5ed37d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "8cf836f4f802b5b5c952b44a975ce89077019b0f7d414287b28ac8aef278bbed"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.x86_64-linux-gnu-cuda+12.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "12"
cuda_platform = "jetson"
git-tree-sha1 = "0fac1d502ed4a8e20784d56d5fef3e755d5e2e75"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "1aad4f57c53edf29ae399647b84e51cac2cfc4ef2d27d949853349a08180a6fe"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "12"
cuda_platform = "sbsa"
git-tree-sha1 = "abca0e9a65269b44596a2354e210a6a4275262a0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "ad273202913ce72ef419bc3f2d51405dceeecaff451ef803fa0c6267256543fe"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "12"
git-tree-sha1 = "4cdd2ff76b0338af55c58fba1ff9ac206b1f45ea"
lazy = true
os = "windows"

    [[CUDA_Compiler.download]]
    sha256 = "9f3cc22997dec0f1b739077c4a9b98902dae881abcc72b9bf9b5971a71dc9738"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.x86_64-w64-mingw32-cuda+12.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "13"
git-tree-sha1 = "2361d4840756cc798f21d1cb0ab19296560e7c29"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "e37529172b930ee8331735c84fba63d1f38ef4b2cd0ce8f433457541c05b4460"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.x86_64-linux-gnu-cuda+13.tar.gz"
[[CUDA_Compiler]]
arch = "aarch64"
cuda = "13"
git-tree-sha1 = "279f01d124cf2ca8d8bfcce01c80b77885631f35"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Compiler.download]]
    sha256 = "1296cdca8430d78752b5cc7d1bd1ba0d70d1c45381513d9992ce482059c03d63"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.aarch64-linux-gnu-cuda+13.tar.gz"
[[CUDA_Compiler]]
arch = "x86_64"
cuda = "13"
git-tree-sha1 = "b5440929dc59b75ba18f62168af47619107b38a9"
lazy = true
os = "windows"

    [[CUDA_Compiler.download]]
    sha256 = "a70911ca0ecd53207ca1e48f91fb9d20a24b64a258ec9b920ae07103aebb8464"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/releases/download/CUDA_Compiler-v0.3.1+1/CUDA_Compiler.v0.3.1.x86_64-w64-mingw32-cuda+13.tar.gz"
