# Autogenerated wrapper script for CUDA_Compiler_jll for x86_64-w64-mingw32-cuda+13.1
export libcudadevrt, libdevice, libnvJitLink, libnvrtc, libnvrtc_builtins, libnvvm, nvdisasm, nvlink, ptxas, tileiras

using CUDA_Driver_jll
JLLWrappers.@generate_wrapper_header("CUDA_Compiler")
JLLWrappers.@declare_file_product(libcudadevrt)
JLLWrappers.@declare_file_product(libdevice)
JLLWrappers.@declare_library_product(libnvJitLink, "nvJitLink_130_0.dll")
JLLWrappers.@declare_library_product(libnvrtc, "nvrtc64_130_0.dll")
JLLWrappers.@declare_library_product(libnvrtc_builtins, "nvrtc-builtins64_131.dll")
JLLWrappers.@declare_library_product(libnvvm, "nvvm64_40_0.dll")
JLLWrappers.@declare_executable_product(nvdisasm)
JLLWrappers.@declare_executable_product(nvlink)
JLLWrappers.@declare_executable_product(ptxas)
JLLWrappers.@declare_executable_product(tileiras)
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Driver_jll)
    JLLWrappers.@init_file_product(
        libcudadevrt,
        "lib\\cudadevrt.lib",
    )

    JLLWrappers.@init_file_product(
        libdevice,
        "nvvm\\libdevice\\libdevice.10.bc",
    )

    JLLWrappers.@init_library_product(
        libnvJitLink,
        "bin\\nvJitLink_130_0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvrtc,
        "bin\\nvrtc64_130_0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvrtc_builtins,
        "bin\\nvrtc-builtins64_131.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvvm,
        "nvvm\\bin\\x64\\nvvm64_40_0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        nvdisasm,
        "bin\\nvdisasm.exe",
    )

    JLLWrappers.@init_executable_product(
        nvlink,
        "bin\\nvlink.exe",
    )

    JLLWrappers.@init_executable_product(
        ptxas,
        "bin\\ptxas.exe",
    )

    JLLWrappers.@init_executable_product(
        tileiras,
        "bin\\tileiras.exe",
    )

    JLLWrappers.@generate_init_footer()
    global cuda_version = v"13.1"
end  # __init__()
