# Autogenerated wrapper script for CUDA_Compiler_jll for x86_64-linux-gnu-cuda+13
export libcudadevrt, libdevice, nvdisasm, nvlink, ptxas, tileiras

using CUDA_Driver_jll
JLLWrappers.@generate_wrapper_header("CUDA_Compiler")
JLLWrappers.@declare_file_product(libcudadevrt)
JLLWrappers.@declare_file_product(libdevice)
JLLWrappers.@declare_executable_product(nvdisasm)
JLLWrappers.@declare_executable_product(nvlink)
JLLWrappers.@declare_executable_product(ptxas)
JLLWrappers.@declare_executable_product(tileiras)
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Driver_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_file_product(
        libcudadevrt,
        "lib/libcudadevrt.a",
    )

    JLLWrappers.@init_file_product(
        libdevice,
        "share/libdevice/libdevice.10.bc",
    )

    JLLWrappers.@init_executable_product(
        nvdisasm,
        "bin/nvdisasm",
    )

    JLLWrappers.@init_executable_product(
        nvlink,
        "bin/nvlink",
    )

    JLLWrappers.@init_executable_product(
        ptxas,
        "bin/ptxas",
    )

    JLLWrappers.@init_executable_product(
        tileiras,
        "bin/tileiras",
    )

    JLLWrappers.@generate_init_footer()
    global cuda_version = v"13.1"
end  # __init__()
