# Autogenerated wrapper script for CUDA_Compiler_jll for x86_64-linux-gnu-cuda+11.6
export libcudadevrt, libdevice, libnvrtc, libnvrtc_builtins, libnvvm, nvdisasm, nvlink, ptxas

using CUDA_Driver_jll
JLLWrappers.@generate_wrapper_header("CUDA_Compiler")
JLLWrappers.@declare_file_product(libcudadevrt)
JLLWrappers.@declare_file_product(libdevice)
JLLWrappers.@declare_library_product(libnvrtc, "libnvrtc.so.11.2")
JLLWrappers.@declare_library_product(libnvrtc_builtins, "libnvrtc-builtins.so.11.6")
JLLWrappers.@declare_library_product(libnvvm, "libnvvm.so.4")
JLLWrappers.@declare_executable_product(nvdisasm)
JLLWrappers.@declare_executable_product(nvlink)
JLLWrappers.@declare_executable_product(ptxas)
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Driver_jll)
    JLLWrappers.@init_file_product(
        libcudadevrt,
        "lib/libcudadevrt.a",
    )

    JLLWrappers.@init_file_product(
        libdevice,
        "nvvm/libdevice/libdevice.10.bc",
    )

    JLLWrappers.@init_library_product(
        libnvrtc,
        "lib/libnvrtc.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvrtc_builtins,
        "lib/libnvrtc-builtins.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvvm,
        "nvvm/lib64/libnvvm.so",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        nvdisasm,
        "bin/nvdisasm",
    )

    JLLWrappers.@init_executable_product(
        nvlink,
        "bin/nvlink",
    )

    JLLWrappers.@init_executable_product(
        ptxas,
        "bin/ptxas",
    )

    JLLWrappers.@generate_init_footer()
    global cuda_version = v"11.6"
end  # __init__()
