# Autogenerated wrapper script for CUDA_Compiler_jll for x86_64-w64-mingw32-cuda+11.7
export libcudadevrt, libdevice, libnvrtc, libnvrtc_builtins, libnvvm, nvdisasm, nvlink, ptxas

using CUDA_Driver_jll
JLLWrappers.@generate_wrapper_header("CUDA_Compiler")
JLLWrappers.@declare_file_product(libcudadevrt)
JLLWrappers.@declare_file_product(libdevice)
JLLWrappers.@declare_library_product(libnvrtc, "nvrtc64_112_0.dll")
JLLWrappers.@declare_library_product(libnvrtc_builtins, "nvrtc-builtins64_117.dll")
JLLWrappers.@declare_library_product(libnvvm, "nvvm64_40_0.dll")
JLLWrappers.@declare_executable_product(nvdisasm)
JLLWrappers.@declare_executable_product(nvlink)
JLLWrappers.@declare_executable_product(ptxas)
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Driver_jll)
    JLLWrappers.@init_file_product(
        libcudadevrt,
        "lib\\cudadevrt.lib",
    )

    JLLWrappers.@init_file_product(
        libdevice,
        "nvvm\\libdevice\\libdevice.10.bc",
    )

    JLLWrappers.@init_library_product(
        libnvrtc,
        "bin\\nvrtc64_112_0.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvrtc_builtins,
        "bin\\nvrtc-builtins64_117.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvvm,
        "nvvm\\bin\\nvvm64_40_0.dll",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        nvdisasm,
        "bin\\nvdisasm.exe",
    )

    JLLWrappers.@init_executable_product(
        nvlink,
        "bin\\nvlink.exe",
    )

    JLLWrappers.@init_executable_product(
        ptxas,
        "bin\\ptxas.exe",
    )

    JLLWrappers.@generate_init_footer()
    global cuda_version = v"11.7"
end  # __init__()
